sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import settings
from women.views import page_not_found

from django.contrib.sitemaps.views import sitemap

from women.sitemaps import PostSitemap, CategorySitemap

sitemaps = {
    'posts': PostSitemap,
    'categories': CategorySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Известные женщины мира'

sitewomen/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterUser.as_view(), name='register'),

    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                                              success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

sitewomen/women/urls.py
from django.urls import path, register_converter
from . import views, converters
from django.views.decorators.cache import cache_page


register_converter(converters.FourDigitYearConverter, 'year4')

urlpatterns = [
    path('', views.WomenHome.as_view(), name='home'),
    # path('', cache_page(20)(views.WomenHome.as_view()), name='home'),  # -> Для кэширования отдельного представления
    path('about/', views.WomenAbout.as_view(), name='about'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    # path('contact/', views.WomenContact.as_view(), name='contact'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    # path('login/', views.login, name='login'),
    path('category/<slug:cat_slug>/', views.WomenCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.WomenTags.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),
]

sitewomen/women/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.urls import reverse

from transliterate import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)


class Women(models.Model):

    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг',
                            validators=[
                               MinLengthValidator(5, message='Минимум 5 символов'),
                               MaxLengthValidator(100, message='Максимум 100 символов')
                            ])
    content = models.TextField(blank=True, verbose_name='Текст статьи')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    is_published = models.BooleanField(default=Status.DRAFT, choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)), verbose_name='Статус')

    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', default=None, blank=True, null=True, verbose_name='Фото')

    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name='Категория')
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name='Теги')
    husband = models.OneToOneField('Husband', on_delete=models.SET_NULL, null=True, blank=True, related_name='husband', verbose_name='Муж')

    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='posts', null=True, default=None)

    objects = models
    published = PublishedManager()

    class Meta:
        verbose_name = 'Известные женщины'
        verbose_name_plural = 'Известные женщины'

        ordering = ['time_create']
        indexes = [
            models.Index(fields=['time_create'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        if self.is_published == self.Status.PUBLISHED:
            return reverse('post', kwargs={'post_slug': self.slug})
        else:
            return reverse('home')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.title))
        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг')

    objects = models.Manager()

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True, verbose_name='Тэг поста')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Слаг')

    objects = models.Manager()

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})


class Husband(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя мужа')
    age = models.IntegerField(null=True, verbose_name='Возраст мужа')
    m_count = models.IntegerField(blank=True, default=0, verbose_name='Количество женидьб')

    objects = models.Manager()

    def __str__(self):
        return self.name


# class UploadFiles(models.Model):
#     """Модель загрузки файла"""
#     file = models.FileField(upload_to='uploads_model')


class ContactMessage(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.EmailField(verbose_name='Почта')
    message = models.TextField(verbose_name='Сообщение')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Сообщения пользователей'
        verbose_name_plural = 'Сообщений пользователей'

    def __str__(self):
        return f"{self.name} - {self.email}"

sitewomen/women/views.py
# from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, Http404, \
    JsonResponse  # , Http404, HttpResponseRedirect, HttpResponsePermanentRedirect
# from django.urls import reverse
# from django.template.loader import render_to_string
from django.urls import reverse_lazy
# from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView

from .forms import *

from .models import *

# import uuid
from .utils import DataMixin, PaginatorFromWomen, CustomPermissionRequiredMixin

# <!-- Кэширование на уровне API -->
# from django.core.cache import cache


class WomenHome(DataMixin, ListView):
    model = Women
    template_name = 'women/index.html'
    context_object_name = 'posts'
    title_page = 'Главная страница'
    cat_selected = 0
    paginator_class = PaginatorFromWomen

    def get_queryset(self):
        # <!-- Кэширование на уровне API -->
        # w_lst = cache.get('women_posts')
        # if not w_lst:
        #     w_lst = Women.published.all().select_related('cat')
        #     cache.set('women_posts', w_lst, 20)
        return Women.published.all().select_related('cat')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', 1)
        paginator = self.paginator_class(self.get_queryset(), self.paginate_by)
        paginator.page(page)
        return self.get_mixin_context(context)


class WomenAbout(DataMixin, TemplateView):
    template_name = 'women/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_selected'] = None
        return self.get_mixin_context(context, title='О нас')


# Обработчик исключений запросов
def page_not_found(request, exception):
    return HttpResponseNotFound(f'<h1>Страница не найдена</h1>')


class ShowPost(DataMixin, DetailView):
    template_name = 'women/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        return get_object_or_404(Women.published, slug=self.kwargs[self.slug_url_kwarg])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title=context['post'].title)


class AddPage(CustomPermissionRequiredMixin, LoginRequiredMixin, DataMixin, CreateView):
    """Класс представления для отображения страницы добавления поста. Наследованный от CreateView."""
    form_class = AddPostForm
    template_name = 'women/addpage.html'
    title_page = 'Добавление статьи'
    extra_context = {'cat_selected': None}
    # login_url = '/admin/'
    permission_required = 'women.add_women'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdatePage(PermissionRequiredMixin, DataMixin, UpdateView):
    """Класс представления для отображения страницы редактирования поста. Наследованный от CreateView."""
    model = Women
    fields = '__all__'
    template_name = 'women/addpage.html'
    success_url = reverse_lazy('home')
    title_page = 'Редактирование статьи'
    permission_required = 'women.change_women'


class DeletePage(DataMixin, DeleteView):
    model = Women
    template_name = 'women/delete_page.html'
    success_url = reverse_lazy('home')
    context_object_name = 'post'

    # def get_object(self, queryset=None):
    #     return Women.objects.get(slug=self.kwargs['slug'])

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return self.get_mixin_context(context, title='Удаление статьи')


class ContactFormView(DataMixin, FormView):
    template_name = 'women/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_selected'] = None
        return self.get_mixin_context(context, title='Контакты')


# class ContactFormView(LoginRequiredMixin, DataMixin, FormView):
#     form_class = ContactForm
#     template_name = 'women/contact.html'
#     success_url = reverse_lazy('home')
#     title_page = 'Обратная связь'
#
#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['cat_selected'] = None
#         return self.get_mixin_context(context, title='Контакты')


class WomenCategory(DataMixin, ListView):
    model = Category
    template_name = 'women/index.html'
    context_object_name = 'posts'
    allow_empty = True
    paginator_class = PaginatorFromWomen

    def get_queryset(self):
        return Women.published.filter(cat__slug=self.kwargs['cat_slug']).select_related('cat')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = context['posts'][0].cat
        page = self.request.GET.get('page', 1)
        paginator = self.paginator_class(self.get_queryset(), self.paginate_by)
        paginator.page(page)

        return self.get_mixin_context(context, title=f'Категория - {cat.name}', cat_selected=cat.pk)


class WomenTags(DataMixin, ListView):
    model = TagPost
    template_name = 'women/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        return Women.published.filter(tags__slug=self.kwargs['tag_slug']).select_related('cat')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = get_object_or_404(TagPost, slug=self.kwargs['tag_slug'])
        return self.get_mixin_context(context, title=f'Тэг - {tag.tag}', cat_selected=None)

sitewomen/women/templates/women/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

<!--      enc-type="multipart/form-data" - без этого, передача файла/ов не будет работать  -->
<!--    <form action="" method="post" enctype="multipart/form-data">-->
<!--        {# {% csrf_token %} #}-->
<!--        <p><input type="file" name="file_upload"></p>-->
<!--        {# {{ form.as_p }} #}-->
<!--        <p><button type="submit">Отправить</button></p>-->
<!--    </form>-->

  <section>
        <h3>Наша миссия</h3>
        <p>Мы создали этот веб-сайт с целью поднятия достойного внимания к историям и достижениям известных женщин мира. Наша миссия - вдохновлять и освещать их удивительные вклады в различные области.</p>
    </section>
    <section>
        <h3>Кто мы</h3>
        <p>Мы - команда энтузиастов, разделяющих увлечение и восхищение перед великими женскими личностями. Наша цель - раскрывать удивительные истории жизни, достижения и влияние известных женщин.</p>
    </section>
    <section>
        <h3>Наша история</h3>
        <p>Наш сайт начал свою деятельность в 2023 году. С тех пор мы посвящаем себя рассказам о сильных и влиятельных женщинах, которые оставили свой след в истории.</p>
    </section>
    <section>
        <h3>Что мы предлагаем</h3>
        <ul>
            <li>Статьи о замечательных женщинах в истории и современности.</li>
            <li>Инсайты и анализ их влияния на общество.</li>
            <li>Вдохновляющие рассказы о жизни и достижениях.</li>
        </ul>
    </section>

<!--    {# {% for item in page_obj %} #} -->
<!--        <p>{# {{ item.pk }}: {{ item.title }} #}</p>-->
<!--    {# {% endfor %} #} -->
<!--    <nav>-->
<!--        <ul>-->
<!--            {# {% for p in page_obj.paginator.page_range %} #} -->
<!--            <li>-->
<!--                {# <a href="?page={{ p }}">{{ p }}</a> #} -->
<!--            </li>-->
<!--            {# {% endfor %} #} -->
<!--        </ul>-->
<!--    </nav>-->
{% endblock %}

sitewomen/women/templates/women/addpage.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Отправить</button></p>
    </form>
{% endblock %}

sitewomen/women/templates/women/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Отправить</button></p>
    </form>
{% endblock %}

sitewomen/women/templates/women/delete_page.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Вы уверены, что хотите удалить "{{ post }}"?</p>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input class="form-button" type="submit" value="Подтвердить">
    </form>
    <a class="a" href="{% url 'post' post_slug=object.slug %}"><input class="form-button" type="submit" value="Отмена"></a>
{% endblock %}

sitewomen/women/templates/women/forbidden.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>{{ text }}</p>
{% endblock %}

sitewomen/women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
<!--  {# {% for p in object_list %} #}  -->
		<li>
			<div class="article-panel">
				<p class="first">Категория: {{ p.cat.name }} | Автор: {{ p.author.username|default:"Неизвестен" }}</p>
				<p class="last">Дата: {{ p.time_update | date:"d-m-Y H:i:s" }}</p>
			</div>
			{% if p.photo %}
        		<p><img class="img-article-left" src="{{ p.photo.url }}"></p>
    		{% endif %}
			<h2>{{ p.title }}</h2>
			{% autoescape off %}
				{{ p.content | linebreaks | truncatewords:50 }}
			{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
		</li>
	{% endfor %}
</ul>
{% endblock %}

{% block navigation %}
	{% if page_obj.has_other_pages %}
		<nav class="list-pages">
			<ul>
				{% if page_obj.has_previous %}
					<li class="page-num">
						<a href="?page=1">&lt;&lt;</a>
					</li>
					<li class="page-num">
						<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
					</li>
				{% endif %}
				{% for p in paginator.page_range %}
					{% if page_obj.number == p %}
						<li class="page-num page-num-selected">{{ p }}</li>
					{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
						<li class="page-num"><a href="?page={{ p }}">{{ p }}</a></li>
					{% endif %}
				{% endfor %}
				{% if page_obj.has_next %}
					<li class="page-num">
						<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
					</li>
					<li class="page-num">
						<a href="?page={{ page_obj.paginator.num_pages }}">&gt;&gt;</a>
					</li>
				{% endif %}
			</ul>
		</nav>
	{% endif %}
{% endblock %}

sitewomen/women/templates/women/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
    {% with post.tags.all as tags %}
        {% if tags %}
            <ul class="tags-list">
                <li>Тэги:</li>
                {% for t in tags %}
                    <li><a href="{{ t.get_absolute_url }}">{{ t.tag }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    {% if post.photo %}
        <p><img class="img-article-left" src="{{ post.photo.url }}"></p>
    {% endif %}
    <p>{{ post.content | linebreaks }}</p>
    {% if user.is_superuser or user == post.author %}
        <a href="{% url 'edit_page' slug=post.slug %}"><input class="form-button" type="button" value="Редактировать"></a>
        <a href="{% url 'delete_page' slug=post.slug %}"><input class="form-button" type="button" value="Удалить"></a>
    {% else %}
        {% if perms.women.change_women %}
            <a href="{% url 'edit_page' slug=post.slug %}"><input class="form-button" type="button" value="Редактировать"></a>
        {% endif %}
        {% if perms.women.delete_women %}
            <a href="{% url 'delete_page' slug=post.slug %}"><input class="form-button" type="button" value="Удалить"></a>
        {% endif %}
    {% endif %}
{% endblock %}